site_name: Help
site_url: https://github.com/moikoros/help/
repo_name: infinite/help
repo_url: https://github.com/moikoros/help

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: current-dark
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/theme/current.css
  - assets/theme/colors.css
  - assets/theme/code.css
  - assets/theme/paragraph.css
  - assets/theme/page.css
  - assets/theme/admonition.css
  - assets/style.css

nav:
  - General: index.md
  - Infinite Yield:
    - Questions: inf/questions.md
    - Executing: inf/executing.md
    - Getting Plugins: inf/gettingplugins.md
    - Installing Plugins: inf/installingplugins.md
    - Using Plugins: inf/usingplugins.md
    - Creating Plugins: inf/creatingplugins.md
    - Plugin Functions: inf/pluginfunctions.md
  - Lua Resources: luaresources.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
